sonar.projectKey=santanusinha_sai
sonar.projectName=sai
sonar.projectVersion=1.0-SNAPSHOT
sonar.organization=santanusinha

sonar.host.url=https://sonarcloud.io

# Sources and tests
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.source=17

# Compiled classes (required for Java analysis)
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Exclusions
sonar.exclusions=**/*.xml,**/*.yaml,**/*.yml,**/*.json
